### ISSUE TITLE
Make this project forked from the original author's repo

### ISSUE THREAD

**Issue by muojp** [muojp/mhz100q-deprecated#2]
The problem is the original author didn't post code on GitHub.

**Comment by muojp** [comment]
@joe1505 Hi, I'm forking your product mhz100q to support KiCad 4.0.x and make some modifications (such as Zynq support). I think it would be great to organize fork network on GitHub to respect original author (you), so could you create mhz100q repository on your (or your company's) account so I will be able to make my repo forked from yours?

**Comment by joe1505** [comment]
@muojp I just created a repo at https://github.com/joe1505/mhz100q. It's currently empty. It's be a day or so before I have time to finish setting things up.
Joe

**Comment by joe1505** [comment]
OK, I deleted the empty repository and replaced it with a clone of the SF SVN repository. First time I've used the github "import repository" tool -  looks like everything's there and it should be ready to go.

**Comment by muojp** [comment]
@joe1505 thank you so much! 🙇  I renamed this (old) repository and made another fork: https://github.com/muojp/mhz100q
Now I'll migrate my issues to new repo.

**Comment by muojp** [comment]
Finished migration. I really appreciate your great work (mhz100q) and support!
